# Generated by Django 4.0.3 on 2022-03-22 12:16

import core.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import timezone_field.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(regex='^7\\d{10}$')], verbose_name='номер телефона клиента')),
                ('time_zone', timezone_field.fields.TimeZoneField(blank=True, choices_display='WITH_GMT_OFFSET', default='Europe/Minsk', verbose_name='часовой пояс')),
            ],
        ),
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField(auto_now=True, verbose_name='дата и время запуска рассылки')),
                ('text', models.TextField(verbose_name='текст сообщения для доставки клиенту')),
                ('stop_datetime', models.DateTimeField(verbose_name='дата и время окончания рассылки')),
            ],
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('operator_code', models.PositiveSmallIntegerField(primary_key=True, serialize=False, verbose_name='мобильный оператор')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tag', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='тэг')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('status', models.CharField(choices=[(core.models.StatusChoice['OK'], 'отправлено'), (core.models.StatusChoice['NO'], 'не доставлен')], max_length=5, verbose_name='статус отправки')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.client', verbose_name='id клиента')),
                ('distribution', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.distribution', verbose_name='id рассылки')),
            ],
        ),
        migrations.AddField(
            model_name='distribution',
            name='filter_operators',
            field=models.ManyToManyField(blank=True, related_name='distribution', to='core.operator', verbose_name='фильтр операторов клиентов для рассылки'),
        ),
        migrations.AddField(
            model_name='distribution',
            name='filter_tags',
            field=models.ManyToManyField(blank=True, related_name='distribution', to='core.tag', verbose_name='фильтр тегов клиентов для рассылки'),
        ),
        migrations.AddField(
            model_name='client',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='core.operator', verbose_name='мобильный оператор'),
        ),
        migrations.AddField(
            model_name='client',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='core.tag', verbose_name='тэг(произвольная метка)'),
        ),
    ]
