# Generated by Django 4.0.3 on 2022-03-22 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_client_tag_client_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='clients', to='core.tag', verbose_name='тэг(произвольная метка)'),
        ),
    ]
